### ISSUE TITLE
Introduce TryHook, that is similar to a playground, but also support validation

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumukit#58]
Try should be similar to Query requests, but should support a `goal` field, with a test specified in a limited validation framework, that only support the following postconditions:

* `last_query_equals`: the query validation passes when the student enters an exact query - whitespaces should be squashed
* `last_query_matches`: the query validation passes when the student enters a query that matches a regexp
* `last_query_fails`, `last_query_passes` the entered query fails or passes
* `query_fails`, `query_passes` a given query fails or passes
* `query_outputs` a given query outputs a given string. 

Some examples:

```json
{
     "language": "javascript",
     "query": "console.log('hola mundo')",
     "cookie": [],
     "goal": {
          "last_query_outputs": "hola mundo"
      }
}
```

```json
{
     "language": "bash",
     "query": "git commit -m foo",
     "cookie": ["cd bar", "git init", "touch baz", "git add baz"],
     "goal": {
          "query_outputs": {  
               "query": "cd bar && git log | grep commit  | wc -l",
               "output": "1"
         }
      }
}
```

**Comment by flbulgarelli** [comment]
After some discussion, we have decided that the goal structure should be more regular: 

```yaml
goal: 
  kind: last_query_passes
```

```yaml
goal: 
  kind: last_query_outputs,
  output: sdsada
```

```yaml
goal: 
  kind: query_outputs,
  query: sdsada,
  output: sasas
```

```yaml
goal: 
  kind: query_passes 
  query: ls -l
  output: foo bar baz
```
